import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import SideBar from "@/components/SideBar";
import { cn } from "@/lib/utils";
import Header from "@/components/Header";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Dashboard",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={cn("flex min-h-screen flex-1", inter.className)}
      >
        <SideBar />
        <div className="flex h-full w-full flex-1 flex-col">
          <Header />
          <div className="p-8 flex flex-1 flex-col">{children}</div>
        </div>
      </body>
    </html>
  );
}
