import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import SideBar from "@/components/SideBar";
import { cn } from "@/lib/utils";
import Header from "@/components/Header";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Dashboard",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={cn("max-h-screen w-full flex", inter.className)}>
        <SideBar />
        <div className="w-full h-full grid">
          <Header />
          <div className="p-8 h-full flex-grow">{children}</div>
        </div>
      </body>
    </html>
  );
}
